name: Helen Lin
markdown: kramdown

url: "/helenlincodes"
css: "/assets/css/main.css"

email: "helen.m.lin@mail.mcgill.ca"
linkedin: "https://linkedin.com/in/helen-m-lin/"
github: "https://github.com/helen-m-lin"
hackerrank: "https://www.hackerrank.com/helen_m_lin"